package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.AwsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.awsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "PROJECT_EXT_26"
                name = "Docker Registry Local"
                userName = "dariakrup"
                password = "credentialsJSON:f542aff8-3ffb-4261-aa16-ec09ee610f31"
            }
        }
        feature1.apply {
            password = "credentialsJSON:c0cceabb-3e54-4eb4-8f1d-b36db6e167ef"
        }
        val feature2 = find<AwsConnection> {
            awsConnection {
                id = "TokenManagementComputationalComplexes_AmazonWebServicesAwsLocal"
                name = "Amazon Web Services (AWS) Local"
                regionName = "eu-west-1"
                credentialsType = static {
                    accessKeyId = "AKIA5JH2VERVI62P5XDY"
                    secretAccessKey = "credentialsJSON:c758ca1d-ccfb-4180-a136-53b3aa8941f9"
                    stsEndpoint = "https://sts.eu-west-1.amazonaws.com"
                }
                allowInSubProjects = true
                allowInBuilds = true
            }
        }
        feature2.apply {
        }
    }
}
