jobs:
  Job1:
    name: Job check
    steps:
      - type: script
        name: Check lab5 file
        script-content: echo ./lab_5/snew.txt
    parameters:
      env.JOB: fifth
parameters:
  labNumber: '5'
